### ISSUE TITLE
Unable to run the asciidoc-to-revealjs-example

### ISSUE THREAD

**Issue by mattbertolini** [asciidoctor/asciidoctor-maven-examples#62]
I apologize if this is the wrong place. I'm pretty sure I am missing something obvious.

I cloned the repo (`master` branch) and tried to run the`asciidoc-to-revealjs-example` and I get the following build failure.

Environment: Mac OS X 10.12.6, Oracle Java 1.8.0_144 x64,  Maven 3.5.0. No changes were made after cloning.

Command: `mvn -e`

Error output:
```
[ERROR] Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:1.5.5:process-asciidoc (generate-slides) on project asciidoc-to-revealjs-example: Execution generate-slides of goal org.asciidoctor:asciidoctor-maven-plugin:1.5.5:process-asciidoc failed: org.jruby.exceptions.RaiseException: (RuntimeError) Could not find a converter to handle transform: document -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:1.5.5:process-asciidoc (generate-slides) on project asciidoc-to-revealjs-example: Execution generate-slides of goal org.asciidoctor:asciidoctor-maven-plugin:1.5.5:process-asciidoc failed: org.jruby.exceptions.RaiseException: (RuntimeError) Could not find a converter to handle transform: document
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution generate-slides of goal org.asciidoctor:asciidoctor-maven-plugin:1.5.5:process-asciidoc failed: org.jruby.exceptions.RaiseException: (RuntimeError) Could not find a converter to handle transform: document
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: org.asciidoctor.internal.AsciidoctorCoreException: org.jruby.exceptions.RaiseException: (RuntimeError) Could not find a converter to handle transform: document
	at org.asciidoctor.internal.JRubyAsciidoctor.renderFile(JRubyAsciidoctor.java:347)
	at org.asciidoctor.maven.AsciidoctorMojo.renderFile(AsciidoctorMojo.java:398)
	at org.asciidoctor.maven.AsciidoctorMojo.execute(AsciidoctorMojo.java:217)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
Caused by: org.jruby.exceptions.RaiseException: (RuntimeError) Could not find a converter to handle transform: document
	at RUBY.find_converter(/Users/example/.m2/repository/org/asciidoctor/asciidoctorj/1.5.6/asciidoctorj-1.5.6.jar!/gems/asciidoctor-1.5.6.1/lib/asciidoctor/converter/composite.rb:52)
	at RUBY.converter_for(/Users/example/.m2/repository/org/asciidoctor/asciidoctorj/1.5.6/asciidoctorj-1.5.6.jar!/gems/asciidoctor-1.5.6.1/lib/asciidoctor/converter/composite.rb:41)
	at RUBY.convert(/Users/example/.m2/repository/org/asciidoctor/asciidoctorj/1.5.6/asciidoctorj-1.5.6.jar!/gems/asciidoctor-1.5.6.1/lib/asciidoctor/converter/composite.rb:31)
	at RUBY.convert(/Users/example/.m2/repository/org/asciidoctor/asciidoctorj/1.5.6/asciidoctorj-1.5.6.jar!/gems/asciidoctor-1.5.6.1/lib/asciidoctor/document.rb:1060)
	at RUBY.convert(/Users/example/.m2/repository/org/asciidoctor/asciidoctorj/1.5.6/asciidoctorj-1.5.6.jar!/gems/asciidoctor-1.5.6.1/lib/asciidoctor.rb:1502)
	at RUBY.convert_file(/Users/example/.m2/repository/org/asciidoctor/asciidoctorj/1.5.6/asciidoctorj-1.5.6.jar!/gems/asciidoctor-1.5.6.1/lib/asciidoctor.rb:1575)
	at org.jruby.RubyIO.open(org/jruby/RubyIO.java:1201)
	at RUBY.convert_file(/Users/example/.m2/repository/org/asciidoctor/asciidoctorj/1.5.6/asciidoctorj-1.5.6.jar!/gems/asciidoctor-1.5.6.1/lib/asciidoctor.rb:1575)
	at RUBY.convertFile(<script>:75)
	at org.jruby.gen.InterfaceImpl867085328.convertFile(org/jruby/gen/InterfaceImpl867085328.gen:13)
```

Is there something additional I have to do? Something I am missing? I'm continuing to search and debug but I figured I would ask as well. If I find something out I will post here (or submit a PR with a fix). Thanks in advance for your help.

**Comment by mattbertolini** [comment]
One thing I noticed was the maven plugin version was different than the asciidoctorj version:

```xml
<asciidoctor.maven.plugin.version>1.5.5</asciidoctor.maven.plugin.version>
<asciidoctorj.version>1.5.6</asciidoctorj.version>
```

I changed them to be the same (both 1.5.5 and 1.5.6) and there was no change.

**Comment by abelsromero** [comment]
> I changed them to be the same (both 1.5.5 and 1.5.6)

Seems I totally screwed up during last update. Last versions for both are 1.5.6.

About the issue, it's working on my Mac, all the same as you, but MacOS, is 10.11.6.
Let me update an retry.

**Comment by abelsromero** [comment]
OK. After deleting the `download-maven-plugin` `.cache` dir now I get the same error.
I keep investigating but I'd say it has something to do with https://github.com/asciidoctor/asciidoctor-reveal.js/.

I keep investigating.

PS: upgrading to jRuby 9k does not help

**Comment by abelsromero** [comment]
Fixed.
Templates in `master` branch are no longer located in `templates/slim`, but directly in `templates` change the configuration here https://github.com/asciidoctor/asciidoctor-maven-examples/blob/8b60d672854e1df7708f30fd4731db65e26ff720/asciidoc-to-revealjs-example/pom.xml#L88 and it should work.
They are still in `slim` in v1.0.4 (current stable).

Regarding the example, I see a problem here. The example downloads the code from the master branch, and caches it, so once downloaded it never downloads it again until you delete the cache. Not good for reproducible builds really, I imagine I have been testing against and old version for a looong time.
I'd feel more comfortable pointing to the last stable release or at least, stating that in the README.

**Comment by mattbertolini** [comment]
Thank you very much for your quick response! I removed the slim from the template dir and it started to work.

I agree with you that using the `master` version makes for non-reproducable builds. I have decided to change my version to the stable (1.0.4) to make it as consistent a build as possible. I can now start building my presentation.

Thanks again!
