### ISSUE TITLE
epub not converting -  no such file to load -- kindlegen

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctor-maven-examples#77]
With last versions 1.6.0 & 2.0x, and even with kindlegen in the path, the example fails with the message.

```
[ERROR] Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:1.6.0:process-asciidoc (generate-spine-kf8) on project asciidoctor-epub-example: Execution generate-spine-kf8 of goal org.asciidoctor:asciidoctor-maven-plugin:1.6.0:process-asciidoc failed: org.jruby.exceptions.LoadError: (LoadError) no such file to load -- kindlegen -> [Help 1]
```

env: 
Java version: 11.0.1, vendor: Oracle Corporation, runtime: C:\home\bin\jdk-11.0.1
Default locale: es_ES, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by ysb33r** [comment]
For `1.6` you need `1.5.0-alpha.8.1` and for `2.0.0` it is `1.5.0-alpha.9`

Alsi inteh Gradle plugin we did the following for non-Windows -> https://github.com/asciidoctor/asciidoctor-gradle-plugin/blob/4b61641569afb98c6d56fddbc2665651d0cdaec6/asciidoctor-gradle-jvm-epub/src/main/groovy/org/asciidoctor/gradle/jvm/epub/AsciidoctorEpubTask.groovy#L133

Unfortunately it does not work on Windows due to file locking issues and the way the Epub converter has been written in Ruby.

**Comment by abelsromero** [comment]
Same issue in Linux, setting the environment like this `KINDLEGEN=$(which kindlegen) mvn` makes the example work.

**Comment by abelsromero** [comment]
I get the same error running the gem directly or through asciidoctor (`asciidoctor -b epub3 -r asciidoctor-epub3 -a ebook-format=kf8 spine.adoc`)

```
~/.../docs/asciidoc >>> asciidoctor-epub3 -a ebook-format=kf8 spine.adoc --trace                                                                                                                                           ±[●][upgrade_AsciidoctorJ_and_other_versions]
Traceback (most recent call last):
        17: from /home/----/.rvm/gems/ruby-2.6.4/bin/ruby_executable_hooks:24:in `<main>'
        16: from /home/----/.rvm/gems/ruby-2.6.4/bin/ruby_executable_hooks:24:in `eval'
        15: from /home/----/.rvm/gems/ruby-2.6.4/bin/asciidoctor-epub3:23:in `<main>'
        14: from /home/----/.rvm/gems/ruby-2.6.4/bin/asciidoctor-epub3:23:in `load'
        13: from /home/----/.rvm/gems/ruby-2.6.4/gems/asciidoctor-epub3-1.5.0.alpha.9/bin/asciidoctor-epub3:32:in `<top (required)>'
        12: from /home/----/.rvm/gems/ruby-2.6.4/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:111:in `invoke!'
        11: from /home/----/.rvm/gems/ruby-2.6.4/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:111:in `each'
        10: from /home/----/.rvm/gems/ruby-2.6.4/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:128:in `block in invoke!'
         9: from /home/----/.rvm/gems/ruby-2.6.4/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `convert_file'
         8: from /home/----/.rvm/gems/ruby-2.6.4/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `open'
         7: from /home/----/.rvm/gems/ruby-2.6.4/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `block in convert_file'
         6: from /home/----/.rvm/gems/ruby-2.6.4/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:124:in `convert'
         5: from /home/----/.rvm/gems/ruby-2.6.4/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb:978:in `write'
         4: from /home/----/.rvm/gems/ruby-2.6.4/gems/asciidoctor-epub3-1.5.0.alpha.9/lib/asciidoctor-epub3/converter.rb:41:in `write'
         3: from /home/----/.rvm/gems/ruby-2.6.4/gems/asciidoctor-epub3-1.5.0.alpha.9/lib/asciidoctor-epub3/packager.rb:620:in `package'
         2: from /home/----/.rvm/gems/ruby-2.6.4/gems/asciidoctor-epub3-1.5.0.alpha.9/lib/asciidoctor-epub3/packager.rb:629:in `distill_epub_to_mobi'
         1: from /home/----/.rvm/rubies/ruby-2.6.4/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/home/----/.rvm/rubies/ruby-2.6.4/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- kindlegen (LoadError)
```

@mojavelinux I don't see any related issue in the epub3 repo and mention in the readme, but since epub3 is alpha I am hesitant to file it as an issue. Is the need to setup the `KINDLEGEN` environment var known?

**Comment by diguage** [comment]
I have the same problem in Mac. 

The error message:
```
[INFO] --- asciidoctor-maven-plugin:2.0.0-RC.1:process-asciidoc (generate-kf8) @ truman ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 16 resources
asciidoctor: ERROR: java.util.LinkedList.adoc: image not found or not readable: /path/to/a.png
asciidoctor: ERROR: java.util.LinkedList.adoc: image not found or not readable: /path/to/b.png
Nov 22, 2019 12:31:43 PM org.asciidoctor.jruby.internal.JRubyAsciidoctor convertFile
SEVERE: (LoadError) no such file to load -- kindlegen
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:00 min
[INFO] Finished at: 2019-11-22T12:31:43+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:2.0.0-RC.1:process-asciidoc (generate-kf8) on project truman: Execution generate-kf8 of goal org.asciidoctor:asciidoctor-maven-plugin:2.0.0-RC.1:process-asciidoc failed: org.jruby.exceptions.LoadError: (LoadError) no such file to load -- kindlegen -> [Help 1]
[ERROR]
```

My environment:

```bash
$ which kindlegen                                                                                                                                                                                                                                                                                                                  /usr/local/bin/kindlegen

$ mvn -V                                                                                                                                                                                                                                                                                                                           
Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T23:06:16+08:00)
Maven home: /usr/local/Cellar/maven/3.6.2/libexec
Java version: 1.8.0_212, vendor: Azul Systems, Inc., runtime: /Users/diguage/.sdkman/candidates/java/8.0.212-zulu/jre
Default locale: en_CN, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.1", arch: "x86_64", family: "mac"
```

My pom.xml

```xml
<spring-restdocs-asciidoctor.version>2.0.4.RELEASE</spring-restdocs-asciidoctor.version>
<asciidoctorj.version>2.1.0</asciidoctorj.version>
<asciidoctorj-pdf.version>1.5.0-beta.7</asciidoctorj-pdf.version>
<asciidoctorj-epub3.version>1.5.0-alpha.9</asciidoctorj-epub3.version>
<asciidoctorj-diagram.version>1.5.18</asciidoctorj-diagram.version>
<asciidoctor-maven-plugin.version>2.0.0-RC.1</asciidoctor-maven-plugin.version>
<jruby.version>9.2.9.0</jruby.version>

<plugin>
    <groupId>org.asciidoctor</groupId>
    <artifactId>asciidoctor-maven-plugin</artifactId>
    <version>${asciidoctor-maven-plugin.version}</version>
    <configuration>
        <sourceDirectory>docs</sourceDirectory>
        <requires>
            <require>asciidoctor-diagram</require>
        </requires>
        <attributes>
            <graphvizdot>/usr/local/bin/dot</graphvizdot>
            <sourcedir>${project.build.sourceDirectory}</sourcedir>
            <imagesdir>.</imagesdir>
        </attributes>
    </configuration>
    <executions>
        <execution>
            <id>generate-html</id>
            <phase>generate-resources</phase>
            <goals>
                <goal>process-asciidoc</goal>
            </goals>
            <configuration>
                <backend>html5</backend>
                <doctype>book</doctype>
                <sourceHighlighter>coderay</sourceHighlighter>
                <attributes>
                    <toc>left</toc>
                    <linkcss>false</linkcss>
                    <icons>font</icons>
                </attributes>
            </configuration>
        </execution>
        <execution>
            <id>generate-docbook</id>
            <phase>generate-resources</phase>
            <goals>
                <goal>process-asciidoc</goal>
            </goals>
            <configuration>
                <backend>docbook</backend>
                <doctype>book</doctype>
                <sourceHighlighter>coderay</sourceHighlighter>
                <attributes>
                    <toc>left</toc>
                    <linkcss>false</linkcss>
                    <icons>font</icons>
                </attributes>
            </configuration>
        </execution>
        <execution>
            <id>generate-pdf</id>
            <phase>generate-resources</phase>
            <goals>
                <goal>process-asciidoc</goal>
            </goals>
            <configuration>
                <backend>pdf</backend>
                <sourceHighlighter>coderay</sourceHighlighter>
                <attributes>
                    <icons>font</icons>
                    <pagenums/>
                    <toc/>
                    <idprefix/>
                    <idseparator>-</idseparator>
                </attributes>
            </configuration>
        </execution>
        <execution>
            <id>generate-epub</id>
            <phase>generate-resources</phase>
            <goals>
                <goal>process-asciidoc</goal>
            </goals>
            <configuration>
                <backend>epub3</backend>
                <sourceHighlighter>coderay</sourceHighlighter>
                <sourceDocumentName>index.adoc</sourceDocumentName>
                <attributes>
                    <icons>font</icons>
                </attributes>
            </configuration>
        </execution>
        <execution>
            <id>generate-kf8</id>
            <phase>generate-resources</phase>
            <goals>
                <goal>process-asciidoc</goal>
            </goals>
            <configuration>
                <backend>epub3</backend>
                <sourceHighlighter>coderay</sourceHighlighter>
                <sourceDocumentName>index.adoc</sourceDocumentName>
                <attributes>
                    <ebook-format>kf8</ebook-format>
                    <icons>font</icons>
                </attributes>
            </configuration>
        </execution>
    </executions>
    <dependencies>
        <dependency>
            <groupId>org.asciidoctor</groupId>
            <artifactId>asciidoctorj</artifactId>
            <version>${asciidoctorj.version}</version>
        </dependency>
        <dependency>
            <groupId>org.asciidoctor</groupId>
            <artifactId>asciidoctorj-pdf</artifactId>
            <version>${asciidoctorj-pdf.version}</version>
        </dependency>
        <dependency>
            <groupId>org.asciidoctor</groupId>
            <artifactId>asciidoctorj-epub3</artifactId>
            <version>${asciidoctorj-epub3.version}</version>
        </dependency>
        <dependency>
            <groupId>org.asciidoctor</groupId>
            <artifactId>asciidoctorj-diagram</artifactId>
            <version>${asciidoctorj-diagram.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.restdocs</groupId>
            <artifactId>spring-restdocs-asciidoctor</artifactId>
            <version>${spring-restdocs-asciidoctor.version}</version>
        </dependency>
        <dependency>
            <groupId>org.jruby</groupId>
            <artifactId>jruby-complete</artifactId>
            <version>${jruby.version}</version>
        </dependency>
    </dependencies>
</plugin>
```

**Comment by mojavelinux** [comment]
>  I don't see any related issue in the epub3 repo and mention in the readme, but since epub3 is alpha I am hesitant to file it as an issue. 

That's the very reason you should file an issue.

Though kindlegen will be upgraded in the upcoming release (alpha.10), and tests will also be run on Windows. So I'd watch for alpha.10 to see what happens, and if it's still happening, report a new issue.

**Comment by abelsromero** [comment]
Latest `asciidoctorj-epub3` v1.5.0-alpha.13 fixes the issue on Linux and Windows. On MacOS I found that kindlegen binary is 32bits and MacOs no longer supports it :'( 

thx @slonopotamus for the fix and @robertpanzer for the release!

**Comment by ysb33r** [comment]
> On MacOS I found that kindlegen binary is 32bits and MacOs no longer supports it

Only if you are running Catalina.

**Comment by slonopotamus** [comment]
@abelsromero See [workaround](https://www.amazon.com/gp/feature.html?ie=UTF8&docId=1000765211).

**Comment by abelsalgadoromeroWD** [comment]
> @abelsromero See [workaround](https://www.amazon.com/gp/feature.html?ie=UTF8&docId=1000765211).

I don't see any mention to workarrounds, and that's where I install kindlegen from always.
On executin it says `bad CPU type in executable: ./kindlegen`.

Googling I found some mentiong that https://www.amazon.com/gp/feature.html?ie=UTF8&docId=1003018611 contains a 64 bits inside it. But no stand alone installer is available.

**Comment by abelsalgadoromeroWD** [comment]
OK, it works.
But I had to install KindlePreview3, manually extract the binary and set it in the PATH var.

**Comment by slonopotamus** [comment]
Oh, sorry, I gave wrong URL. It should be https://www.literatureandlatte.com/forum/viewtopic.php?p=284621#p284621

**Comment by abelsromero** [comment]
That's what I ended up findind, thanks 😃  I will add that as a note to the README, I can't really think of anything else better.

**Comment by slonopotamus** [comment]
I've contacted Kindle Direct Publishing support on kindlegen+Catalina issue. If there are any updates on this, I'll post to tdtds/kindlegen#36

**Comment by abelsromero** [comment]
fixed with https://github.com/asciidoctor/asciidoctor-maven-examples/pull/93
